export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const CATALOG_ROUTE = '/catalog'
export const ADMIN_ROUTE = '/admin'
export const REGISTRATION_ROUTE = '/auth'
export const LOGIN_ROUTE = '/auth'
export const PROFILE_ROUTE = '/profile'
export const DEVICEPAGE_ROUTE = '/device'
